export const GET_ALL_PRODUCTS_PENDING = 'GET_ALL_PRODUCTS_PENDING';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILED = 'GET_ALL_PRODUCTS_FAILED';

export const GET_POPULAR_PRODUCTS_PENDING = 'GET_POPULAR_PRODUCTS_PENDING';
export const GET_POPULAR_PRODUCTS_SUCCESS = 'GET_POPULAR_PRODUCTS_SUCCESS';
export const GET_POPULAR_PRODUCTS_FAILED = 'GET_POPULAR_PRODUCTS_FAILED';

export const GET_DETAIL_PRODUCT_PENDING = 'GET_DETAIL_PRODUCT_PENDING';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAILED = 'GET_DETAIL_PRODUCT_FAILED';

export const GET_PROFILE_ID_PENDING = 'GET_PROFILE_ID_PENDING';
export const GET_PROFILE_ID_SUCCESS = 'GET_PROFILE_ID_SUCCESS';
export const GET_PROFILE_ID_FAILED = 'GET_PROFILE_ID_FAILED';

export const GET_STORE_ID_PENDING = 'GET_STORE_ID_PENDING';
export const GET_STORE_ID_SUCCESS = 'GET_STORE_ID_SUCCESS';
export const GET_STORE_ID_FAILED = 'GET_STORE_ID_FAILED';
